export const ProjectData = [
  {
    id: 1,
    Category: 'Web & App design',
    ProjectName: 'E-commerce Website Redesign',
    Location: 'London, UK',
    RandomNumber: 6,
    Amount: 500.0,
    Type: 'Fixed',
  },
  {
    id: 2,
    Category: 'Graphic Design',
    ProjectName: 'Logo Design for Startup',
    Location: 'London, UK',
    Time: '5 hours ago',
    RandomNumber: 3,
    Amount: 30.0,
    Type: 'perHour',
  },
  {
    id: 3,
    Category: 'Mobile App Development',
    ProjectName: 'Fitness Tracking App',
    Location: 'London, UK',
    Time: '1 hour ago',
    RandomNumber: 8,
    Amount: 750.0,
    Type: 'Fixed',
  },
  {
    id: 4,
    Category: 'Writing',
    ProjectName: 'Blog Article Writing',
    Location: 'London, UK',
    Time: '1 hour ago',
    RandomNumber: 2,
    Amount: 120.0,
    Type: 'perHour',
  },
  {
    id: 5,
    Category: 'Video Production',
    ProjectName: 'Promotional Video for Product Launch',
    Location: 'London, UK',
    Time: '6 hours ago',
    RandomNumber: 7,
    Amount: 850.0,
    Type: 'Fixed',
  },
  {
    id: 6,
    Category: 'Social Media Marketing',
    ProjectName: 'Campaign Management',
    Location: 'London, UK',
    Time: '8 hour ago',

    RandomNumber: 5,
    Amount: 40.0,
    Type: 'perHour',
  },
  {
    id: 7,
    Category: 'UI/UX Design',
    ProjectName: 'Mobile App Interface Enhancement',
    Location: 'New York, USA',
    Time: '5 hour ago',
    Time: '2 hours ago',
    RandomNumber: 4,
    Amount: 600.0,
    Type: 'Fixed',
  },
  {
    id: 8,
    Category: 'Content Creation',
    ProjectName: 'Podcast Series Production',
    Location: 'Los , USA',
    Time: '8 hour ago',
    RandomNumber: 9,
    Amount: 20.0,
    Type: 'perHour',
  },
]
